### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by LaurenaRehbein** [SystmWeb/valetpress#3]
Love ValetPress for quick site creation but I find when I visit the new site I'm getting ERR_TOO_MANY_REDIRECTS. If I disable valetpress by renaming the dir at `../wp-content/plugins/valetpress` the site then works fine. 

Thoughts?

**Comment by sdenike** [comment]
@LaurenaRehbein Hey! Glad that you are enjoying it! So I have seen the redirect issue at times when trying to access wp-admin/ directly instead of wp-login.php.  The reason for this is the code in the valetpress plugin has an autologin function, and when trying to get to wp-admin it freaks out ... clearly something I should work on fixing :D ... Another way around this would be to make a new user/password once you get logged in the first time, then you should be able to delete the valetpress plugin or disable it.

**Comment by LaurenaRehbein** [comment]
Ah, interesting! Yup, disabling the `valetpress` plugin takes care of the trouble and I can then login just fine. 

First time around I thought I broke something. But now that I know, it's very little trouble. 

A great setup, I can spin up a test site in 30 seconds flat (which I do now almost daily), AMAZING tool.

**Comment by sdenike** [comment]
I will try to add that to the README on the next release to avoid any confusion/next steps when setting up a site :). Very glad it helps you on a daily basis, the same reason that I worked with Aaron originally on rewriting it all as I test Themes/Plugins all day and was tired of spending 15+ minutes to get a working site setup.  And by all means please open up any other issues/ideas as I would like to expand on the script while making sure not to make it too bloated and unusable.
